# ============================================================
# app.py
# Store Sales Prediction - Streamlit Web Application
#
# Required file in the same folder:
#     sales_model.pkl
#
# The PKL is generated by the final cell of predicting_sales.ipynb
# ============================================================

from pathlib import Path

import joblib
import matplotlib.pyplot as plt
import pandas as pd
import streamlit as st


# ============================================================
# LOAD MODEL PACKAGE
# ============================================================

BASE_DIR = Path(__file__).resolve().parent
MODEL_FILE = BASE_DIR / "sales_model.pkl"

if not MODEL_FILE.exists():
    st.error(
        "sales_model.pkl was not found.\n\n"
        "Run the final model-export cell in predicting_sales.ipynb "
        "first, then place sales_model.pkl beside app.py."
    )
    st.stop()

package = joblib.load(MODEL_FILE)

model = package["model"]
features = package["features"]
store_avg = package["store_avg"]
global_avg = package["global_avg"]
metrics = package["metrics"]


# ============================================================
# SAME FEATURE ENGINEERING USED IN THE NOTEBOOK
# ============================================================

def prepare_features(data):
    df = data.copy()

    df["Date"] = pd.to_datetime(df["Date"], errors="coerce")

    # StateHoliday one-hot encoding
    for value in ["0", "a", "b", "c"]:
        df[f"StateHoliday_{value}"] = (
            df["StateHoliday"].astype(str) == value
        ).astype(int)

    df.drop(columns=["StateHoliday"], inplace=True)

    # Calendar features
    df["Year"] = df["Date"].dt.year
    df["Month"] = df["Date"].dt.month
    df["Day"] = df["Date"].dt.day
    df["WeekOfYear"] = df["Date"].dt.isocalendar().week.astype(int)
    df["Quarter"] = df["Date"].dt.quarter
    df["DayOfYear"] = df["Date"].dt.dayofyear
    df["IsWeekend"] = (df["DayOfWeek"] >= 6).astype(int)

    # Training-only StoreAvgSales
    df["StoreAvgSales"] = (
        df["Store"].map(store_avg).fillna(global_avg)
    )

    return df


def predict_sales(data):
    processed = prepare_features(data)
    return model.predict(processed[features])


# ============================================================
# PAGE CONFIGURATION
# ============================================================

st.set_page_config(
    page_title="Store Sales Prediction",
    page_icon="📈",
    layout="wide"
)


# ============================================================
# SIDEBAR
# ============================================================

st.sidebar.title("Model Information")

st.sidebar.metric("MAE", f"{metrics['MAE']:,.2f}")
st.sidebar.metric("RMSE", f"{metrics['RMSE']:,.2f}")
st.sidebar.metric("R²", f"{metrics['R2']:.4f}")

st.sidebar.markdown("---")
st.sidebar.write(
    f"Training records: **{package['train_records']:,}**"
)
st.sidebar.write(
    f"Evaluation records: **{package['eval_records']:,}**"
)
st.sidebar.write(
    f"Live records: **{package['live_records']:,}**"
)
st.sidebar.write("Model: **Random Forest Regressor**")


# ============================================================
# HEADER
# ============================================================

st.title("📈 Store Sales Prediction")
st.caption(
    "Random Forest model | Rossmann Store Sales"
)


# ============================================================
# TABS
# ============================================================

tab1, tab2, tab3 = st.tabs(
    ["🔮 Single Prediction", "📂 Batch Prediction", "📊 Model Information"]
)


# ============================================================
# 1. SINGLE PREDICTION
# ============================================================

with tab1:

    st.subheader("Predict Store Sales")

    col1, col2, col3 = st.columns(3)

    with col1:

        store = st.number_input(
            "Store ID",
            min_value=1,
            max_value=1115,
            value=5,
            step=1
        )

        date = st.date_input(
            "Date",
            value=pd.Timestamp("2015-07-31")
        )

        customers = st.number_input(
            "Customers",
            min_value=0,
            max_value=7388,
            value=508,
            step=1
        )

    with col2:

        day_of_week = st.selectbox(
            "Day of Week",
            list(range(1, 8)),
            index=4,
            help="1 = Monday, 7 = Sunday"
        )

        open_store = st.selectbox(
            "Store Open",
            [0, 1],
            index=1
        )

        promo = st.selectbox(
            "Promo",
            [0, 1],
            index=1
        )

    with col3:

        school_holiday = st.selectbox(
            "School Holiday",
            [0, 1],
            index=0
        )

        state_holiday = st.selectbox(
            "State Holiday",
            ["0", "a", "b", "c"],
            index=0
        )

    st.markdown("---")

    if st.button("Predict Sales", type="primary"):

        # Closed store → no customers and zero sales
        if open_store == 0:
            customers = 0
            prediction = 0

        else:
            input_data = pd.DataFrame(
                [
                    {
                        "Store": store,
                        "DayOfWeek": day_of_week,
                        "Date": date,
                        "Customers": customers,
                        "Open": open_store,
                        "Promo": promo,
                        "StateHoliday": state_holiday,
                        "SchoolHoliday": school_holiday,
                    }
                ]
            )

            prediction = predict_sales(input_data)[0]

        st.success("Prediction completed!")

        st.metric("Predicted Sales", f"{max(0, prediction):,.0f}")


# ============================================================
# 2. BATCH PREDICTION
# ============================================================

with tab2:

    st.subheader("Batch Sales Prediction")

    st.write(
        "Upload a CSV containing these columns:"
    )

    st.code(
        "Store, DayOfWeek, Date, Customers, Open, Promo, "
        "StateHoliday, SchoolHoliday"
    )

    uploaded_file = st.file_uploader(
        "Upload CSV",
        type=["csv"]
    )

    if uploaded_file is not None:

        batch_df = pd.read_csv(uploaded_file)

        st.write("Input preview:")
        st.dataframe(batch_df.head(10), use_container_width=True)

        required = [
            "Store",
            "DayOfWeek",
            "Date",
            "Customers",
            "Open",
            "Promo",
            "StateHoliday",
            "SchoolHoliday"
        ]

        missing = [
            col for col in required
            if col not in batch_df.columns
        ]

        if missing:

            st.error(
                "Missing columns: " + ", ".join(missing)
            )

        else:

            if st.button("Generate Batch Predictions"):

                predictions = predict_sales(batch_df)

                result = batch_df.copy()
                result["PredictedSales"] = pd.Series(
                    predictions
                ).clip(lower=0)

                st.success(
                    f"Predicted {len(result):,} records."
                )

                st.dataframe(
                    result,
                    use_container_width=True
                )

                csv = result.to_csv(
                    index=False
                ).encode("utf-8")

                st.download_button(
                    "Download Predictions CSV",
                    data=csv,
                    file_name="sales_predictions.csv",
                    mime="text/csv"
                )


# ============================================================
# 3. MODEL INFORMATION
# ============================================================

with tab3:

    st.subheader("Model Information")

    st.write("### Selected Model")
    st.write("**Random Forest Regressor**")

    st.write("### Evaluation Performance")

    metric_df = pd.DataFrame({
        "Metric": ["MAE", "RMSE", "R²"],
        "Value": [
            metrics["MAE"],
            metrics["RMSE"],
            metrics["R2"]
        ]
    })

    st.dataframe(
        metric_df,
        hide_index=True,
        use_container_width=True
    )

    st.write("### Features")

    feature_df = pd.DataFrame({
        "Feature": features
    })

    st.dataframe(
        feature_df,
        hide_index=True,
        use_container_width=True
    )

    st.write("### Feature Importance")

    importance = pd.DataFrame({
        "Feature": features,
        "Importance": model.feature_importances_
    }).sort_values(
        "Importance",
        ascending=False
    )

    fig, ax = plt.subplots(figsize=(9, 6))

    ax.barh(
        importance["Feature"],
        importance["Importance"]
    )

    ax.invert_yaxis()
    ax.set_xlabel("Importance")
    ax.set_title("Random Forest Feature Importance")

    plt.tight_layout()

    st.pyplot(fig)
